Models/TeamMembers.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebFrontToBack.Models
{
    public class TeamMembers
    {

        public int Id { get; set; }
        //[Required(ErrorMessage = "Boş ola bilməz"), MaxLength(50, ErrorMessage = "Uzunluq maximum 50 simvol olmalıdır")]
        public string FullName { get; set; }
        //[Required]
        public string Profession { get; set; }//ixtisas
        //[Required]
        public string ImagePath { get; set; }

        //[Required,NotMapped] //---Miq olma
        //public IFormFile Photo { get; set; }


    }
}

Areas/Admin/Controllers/TeamMembersController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebFrontToBack.Areas.Admin.ViewModels;
using WebFrontToBack.DAL;
using WebFrontToBack.Models;
using WebFrontToBack.Utilities.Constants;
using WebFrontToBack.Utilities.Extensions;

namespace WebFrontToBack.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeamMembersController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        //Environment proyektin unvanini verir birbasha

        public TeamMembersController(AppDbContext context,IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            ICollection<TeamMembers> members = await _context.TeamMembers.ToListAsync();
            return View(members);
            //return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTeamMemberVM member)
        {
            if (!ModelState.IsValid)//-- InValid demek dogru deyilse demekdir.
            {
                return View();
            }
           
            if (!member.Photo.CheckContentType("image/"))
            {
                ModelState.AddModelError("Photo", $"{member.Photo.FileName} {Messages.FileTypeMustBeImage}");
                return View();
            }
            if (!member.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", $"{member.Photo.FileName} - file type must be size less than 200kb");
                return View();
            }

            //string root = _webHostEnvironment.WebRootPath;
            //string resultRoot = Path.Combine(root, "assets", "img");---------//shekilleri save elemeyim ucundur bu setir
            //string fileName=Guid.NewGuid().ToString()+member.Photo.fileName; -----  //bu ise yalniz ve yalniz bazaya elave etmeyim ucundur tek fileNameni elave edirem yeni
             //return Json(fileName);

            string root = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img");
           string fileName = await member.Photo.SaveAsync(root);//shekillerin unvanini verdim
            //string root= _webHostEnvironment.WebRootPath;
            //string fileName = Guid.NewGuid().ToString() + member.Photo.fileName;
            //string resultPath=Path.Combine(root, "assets", "img",fileName);
            //using (FileStream filestream = new FileStream(resultPath, FileMode.Create))
            //{
            //    await member.Photo.CopyToAsync(filestream);
            //}
            TeamMembers teamMember = new TeamMembers()
            {
                FullName = member.FullName,
                ImagePath = fileName,
                Profession = member.Profession
            };
            await _context.TeamMembers.AddAsync(teamMember);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int id)
        {
            TeamMembers member = await _context.TeamMembers.FindAsync(id);
            if (member == null) return NotFound();
            return View(member);
        }

        [HttpPost]
        public async Task<IActionResult> Update(TeamMembers member)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            TeamMembers result = await _context.TeamMembers.FirstOrDefaultAsync(t => t.Id == member.Id);
            if (result is null)
            {
                TempData["Exists"] = "Bu Member bazada yoxdur";
                return RedirectToAction(nameof(Index));
            }
            result.FullName = member.FullName;
            result.Profession = member.Profession;
            result.ImagePath = member.ImagePath;
            _context.TeamMembers.Update(result);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int Id)
        {

            //TeamMember teamMember = await _context.TeamMembers.FindAsync(id);
            //if (teamMember == null) return NotFound();
            //string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img", teamMember.ImagePath);
            //if (System.IO.File.Exists(imagePath))
            //{
            //    System.IO.File.Delete(imagePath);
            //}

            TeamMembers? member = _context.TeamMembers.Find(Id);
            if (member == null)
            {
                return NotFound();
            }
            _context.TeamMembers.Remove(member);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

Areas/Admin/Views/TeamMembers/Create.cshtml
@model CreateTeamMemberVM;

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <form class="forms-sample" method="post" action="create">
                <div class="form-group">
                    <label asp-for="FullName"></label>
                    <input asp-for="FullName" class="form-control" placeholder="TeamMember">
                    <span class="text text-danger" asp-validation-for="FullName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Profession"></label>
                    <input asp-for="Profession" class="form-control" placeholder="TeamMember">
                    <span class="text text-danger" asp-validation-for="Profession"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Photo"></label>
                    <input asp-for="Photo" class="form-control" placeholder="Photo">
                    <span class="text text-danger" asp-validation-for="Photo"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2 text-light">Create</button>
                <button class="btn btn-light" asp-action="Index">Go back</button>

            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/TeamMembers/Index.cshtml
@model ICollection<TeamMembers>
@{
    int count = 1;
}

<div class="d-flex justify-content-end mb-2">
    <a class="btn btn-success text-light" asp-area="Admin" asp-controller="TeamMembers" asp-action="Create">Create Category</a>
</div>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                FullName
                            </th>

                            <th>
                                Profession
                            </th>

                            <th>
                                ImagePath
                            </th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach (TeamMembers item in Model)
                        {
                            <tr>
                                <td> @count</td>

                                <td>
                                    @item.FullName
                                </td>
                                <td>
                                    <a class="btn btn-primary text-light">Detail</a>
                                    <a class="btn btn-warning text-light" asp-area="Admin" asp-controller="TeamMembers" asp-action="Update" asp-route-Id="@item.Id">Update</a>
                                    <a class="btn btn-danger text-light" asp-area="Admin" asp-controller="TeamMembers" asp-action="Delete" asp-route-Id="@item.Id">Delete</a>
                                </td>
                            </tr>
                            count++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/TeamMembers/Update.cshtml
@model TeamMembers;

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="FullName"></label>
                    <input asp-for="FullName" class="form-control" placeholder="TeamMembers">
                    <span class="text text-danger" asp-validation-for="FullName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Profession"></label>
                    <input asp-for="Profession" class="form-control" placeholder="TeamMembers">
                    <span class="text text-danger" asp-validation-for="Profession"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImagePath"></label>
                    <input asp-for="ImagePath" class="form-control" placeholder="TeamMembers">
                    <span class="text text-danger" asp-validation-for="ImagePath"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2 text-light">Update</button>
                <button class="btn btn-light" asp-action="Index">Go back</button>
            </form>
        </div>
    </div>
</div>